MODUL 3

Exercici1
Carregar data i targe del conjunt de dades i mostrar 10 registres

In [1]:
import numpy as np


In [2]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
from sklearn.datasets import load_iris

In [4]:
iris=load_iris()
data = iris.data
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [5]:
target = iris.target
target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Exercici2
Concatenar data i target en un nou array. Mostrar els 5 primers valors

In [6]:
iris.feature_names #puedo acceder al detalle de cada columna

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
iris.target_names  #accedo al tipo de flor

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [8]:
data.shape

(150, 4)

In [9]:
target.shape

(150,)

In [10]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
target.T

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
comb= np.concatenate((data,target.reshape(-1,1)),axis=1) #el reshape em transforma en un array
comb

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

Exercici3
Calcular la mitjana i la desviació mitjana de la longitud del sepal i la longitud del petal. Mostra els resultats amb dos decimals

In [13]:
iris.feature_names #puedo acceder al detalle de cada columna



['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [14]:
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [15]:
media_sepal=np.mean(data[:,0])
media_petal=np.mean(data[:,2])

In [16]:
desv_sepal=np.std(data[:,0])
desv_petal=np.std(data[:,2])


In [17]:
print("Sepal: media",format(media_sepal,".2f"),"desviació",format(desv_sepal,".2f"))
print("Petal: media",format(media_petal,".2f"),"desviació",format(desv_petal,".2f"))

Sepal: media 5.84 desviació 0.83
Petal: media 3.76 desviació 1.76


Exercici 4
Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior. La utilitzaràs d'aquí endavant.

In [18]:
#selecciono aleatòriament 20 valors entre 0-150
index = np.random.choice(150,20)
index



array([147,  84,  40, 134, 125,  98,  53, 144,  96,  29,   9,  81,   7,
       127,  11, 100, 129, 123,  83,  13])

In [19]:
#seleccionen les dades que ocupen la posició dels index
for i in index:
    data_sample=data[index,:]

data_sample

array([[6.5, 3. , 5.2, 2. ],
       [5.4, 3. , 4.5, 1.5],
       [5. , 3.5, 1.3, 0.3],
       [6.1, 2.6, 5.6, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [5.1, 2.5, 3. , 1.1],
       [5.5, 2.3, 4. , 1.3],
       [6.7, 3.3, 5.7, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [4.7, 3.2, 1.6, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.5, 2.4, 3.7, 1. ],
       [5. , 3.4, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [4.8, 3.4, 1.6, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [7.2, 3. , 5.8, 1.6],
       [6.3, 2.7, 4.9, 1.8],
       [6. , 2.7, 5.1, 1.6],
       [4.3, 3. , 1.1, 0.1]])

Exercici 5
Crea una matriu que mostri:  

La mitjana de cada característica per espècie. (mean)
La desviació estàndard de cada característica per espècie. (std)


In [20]:
data_mean=data_sample.mean(axis=0)
data_desv=data_sample.std(axis=0)


In [21]:
resultats = np.vstack((iris.feature_names,data_mean,data_desv))
resultats


array([['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
        'petal width (cm)'],
       ['5.715', '2.975', '3.8600000000000003', '1.2150000000000003'],
       ['0.8119575112036344', '0.3374537005279391', '1.7559612751994276',
        '0.7695940488335392']], dtype='<U32')

Exercici 6
Calcula la quantitat de mostres per espècie.
Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"


In [45]:
setosa = comb[comb[:,4]==0]
setosa.shape


(50, 5)

In [46]:
versicolor = comb[comb[:,4]==1]
versicolor.shape

(50, 5)

In [53]:
virginica = comb[comb[:,4]==2]
virginica.shape

(50, 5)

In [54]:
setosa_max=setosa.max(axis=0)
setosa_max

array([5.8, 4.4, 1.9, 0.6, 0. ])

In [56]:
versicolor_max=versicolor.max(axis=0)
versicolor_max

array([7. , 3.4, 5.1, 1.8, 1. ])

In [57]:
virginica_max=virginica.max(axis=0)
virginica_max

array([7.9, 3.8, 6.9, 2.5, 2. ])

In [58]:

especies_max = np.vstack((setosa_max,versicolor_max,virginica_max))
especies_max


array([[5.8, 4.4, 1.9, 0.6, 0. ],
       [7. , 3.4, 5.1, 1.8, 1. ],
       [7.9, 3.8, 6.9, 2.5, 2. ]])

Exercici 7
Calcula la matriu de correlació entre les variables.
Filtra els valors majors a la mitjana (de l'exercici 3) de la longitud dels pètals i mostra-ho. 
Troba la mostra amb els pètals més llargs.

In [63]:
corr = np.corrcoef(data.T)
corr

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

In [69]:
#media petal
petal_gran=data[data[:,2]>3.76] 
petal_gran



array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.4, 3.8, 1.1],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2

In [71]:
petal_max= petal_gran.max(axis=0)
petal_max

array([7.9, 3.8, 6.9, 2.5])